version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    env_file: ./backend/.env
    volumes:
      - ./backend:/var/www/html
      - ./frontend/public:/var/www/html/public
    networks:
      - app-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: node
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/public:/var/www/html/public
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
